# Generated by Django 5.0 on 2023-12-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_useraccount_delete_mobilecoinaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_keys',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='next_block_to_sync',
            field=models.IntegerField(default=0),
        ),
    ]
