# Generated by Django 5.0 on 2023-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_useraccount_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='account_keys',
            new_name='account_key_id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_main_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_mobilecoin_balance_observed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='recovery_mnemonic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
