# Generated by Django 5.0 on 2024-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='unlock_fee',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
