# Generated by Django 5.0.1 on 2024-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_unlock_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='unlock_fee',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=13),
        ),
    ]
